### ISSUE TITLE
Downgrade doesn't work

### ISSUE THREAD

**Issue by fieldingy** [charyorde/db-migrate-cassandra#2]
Got the following error when try to do a db downgrade :

message: 'Some partition key parts are missing: id',
  info: 'Represents an error message from the server',
  code: 8704,
  coordinator: '10.236.127.33:9042',
  query: 'DELETE FROM "migrations" WHERE name = ?' }
[ERROR] Error: Some partition key parts are missing: id

I think this is because the ID column.  If you removed the id column from the migrations table, then this should work just fine.

**Comment by charyorde** [comment]
Are you trying to drop the `migrations` table or a `cassandra` keyspace?

**Comment by fieldingy** [comment]
I'm trying to drop a cassandra table.   But it doesn't really matter.   My script runs fine.  The problem is that is a downgrade script.  When performing a downgrade, db-migrate will try to remove an entry from migrations table, and db-migrate-cql try to remove the entry by name, but it failed with the error that I have provided.   

    On Wednesday, May 17, 2017 2:37 PM, charyorde <notifications@github.com> wrote:
 

 Are you trying to drop the migrations table or a cassandra table?—

**Comment by charyorde** [comment]
Okay. Please feel free to reopen if you encounter more issues.

**Comment by fieldingy** [comment]
Why this is closed?  Once the downgrade failed, I cannot use this tool to do the upgrade again, because there is an entry in the DB, so the same script cannot be ran again.
